  
version: '3'
services:
  server:
    image: node:latest
    working_dir: /code
    ports: 
      - 3000:3000
    environment: 
      - DB_NAME=telegraph
      - DB_CONNECTION=mongodb://tomandjames:telegraphpass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm start"

  db:
    image: mongo:latest
    volumes:
      - "dbdata:/var/lib/mongodb/data"
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=tomandjames
      - MONGO_INITDB_DATABASE=telegraph
      - MONGO_INITDB_ROOT_PASSWORD=telegraphpass
volumes:
  dbdata: